services:
  catalina:
    image: macos:catalina
    build:
      context: .
      dockerfile: Dockerfile
    container_name: macos-catalina
    environment:
      VERSION: "catalina"
      DISK_SIZE: "256G"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      ARGUMENTS: "-device usb-host,vendorid=0x1234,productid=0x1234"
      BOOT_MODE: "full"
    devices:
      - /dev/kvm
      - /dev/bus/usb
    volumes:
      - ./storage/catalina:/storage
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
