services:
  osx:
    image: macos:toan
    build:
      context: .
      dockerfile: Dockerfile
    container_name: macos
    environment:
      VERSION: "big-sur"
      DISK_SIZE: "256G"
      RAM_SIZE: "6G"
      CPU_CORES: "4"
      ARGUMENTS: "-device usb-host,vendorid=0x1234,productid=0x1234"
    devices:
      - /dev/kvm
      - /dev/bus/usb
    volumes:
      - ./storage:/storage
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
